title: Jasper Taffs
logo: /assets/Profile_pic_circle.png
description: MEng Mechanical Engineer @ University of Leeds
theme: jekyll-theme-minimal
# Add social links
author:
  name: Jasper Taffs
  linkedin: https://www.linkedin.com/in/jasper-taffs-a5b818294/  # or full URL if theme needs it

# Optional: Add to navigation or footer depending on theme
social_links:
  - name: Jasper Taffs
    url: https://www.linkedin.com/in/jasper-taffs-a5b818294/
    icon: fab fa-linkedin
