title: Jasper Taffs
logo: /assets/Profile_pic_circle.png
description: MEng Mechanical Engineer @ University of Leeds
theme: jekyll-theme-minimal

# Social links (used by jekyll-theme-minimal)
social_links:
  - name: LinkedIn
    url: https://www.linkedin.com/in/jasper-taffs-a5b818294/
